# 生产环境
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://119.23.214.198:3306/nowander?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: nowander_user
    password: baotamysql123456
  redis:
    port: 6379
    host: 119.23.214.198
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 8
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0
    client-type: lettuce
    timeout: 10000
    password: 123456
logging:
  file:
    path: /var/logs