@startuml
actor 用户 as  user
participant 页面 as browser
participant 登录Service as loginService
participant 短信服务 as sms
participant 数据库 as db

user -> browser ++: 输入手机号，\n点击获取短信验证码
browser -> sms ++: 发送短信验证码
return ok
user <<- browser --: 短信验证码
user -> browser ++: 输入验证码、账号密码
browser -> loginService ++: 用户登录
loginService -> db ++: 获取用户数据
return 用户数据
loginService -> loginService ++--: 比对用户账号密码
alt 密码正确
    loginService -> loginService++--: 生成JWT
    loginService --> browser: 用户数据和JWT
    browser --> user: 登录成功
else 密码错误
    loginService --> browser--: 用户密码错误提示信息
    browser --> user: 登录失败

end


@enduml