@startuml
left to right direction

actor 系统管理员 as admin
actor 举办方 as organizer
actor 参赛选手 as contestant

usecase (提交用户认证信息) as user_auth_create
usecase (修改用户认证信息) as user_auth_update
organizer --> user_auth_create
contestant --> user_auth_create
organizer --> user_auth_update
contestant --> user_auth_update

usecase (用户身份认证) as user_auth_review
admin --> user_auth_review




@enduml