@startuml
left to right direction

actor 系统管理员 as admin
actor 系统用户 as sysUser
sysUser <|-r- admin

usecase (用户管理) as user_manage
usecase (用户认证) as user_auth
usecase (赛事审核) as competition_review

package 组件 as components {
    usecase (创建组件) as component_create
    usecase (修改组件状态) as component_update_state
    usecase (更新组件信息) as component_update_info
}

package 预设模板 as templates {
    usecase (预设模板发布) as preset_template_publish
    usecase (预设模板更新) as preset_template_update
    usecase (预设模板状态更新) as preset_template_state_update
    usecase (预设模板删除) as preset_template_delete
    usecase (预设模板获取) as preset_template_get
}

admin --> components
admin --> templates
admin --> user_manage
admin --> user_auth
admin --> competition_review

@enduml