@startuml
left to right direction

actor 系统用户 as sysUser
actor 系统管理员 as admin
actor 举办方 as organizer
actor 参赛选手 as contestant

sysUser <|-u- admin
sysUser <|-u- organizer
sysUser <|-u- contestant

usecase (登录) as sign_in
usecase (注册) as sign_up
usecase (账号管理) as user_info_manage

sysUser --> sign_in
sysUser --> sign_up
sysUser --> user_info_manage

@enduml