version: '3'
services:
  # 参考：
  # https://juejin.cn/post/6844903872557760526
  # https://blog.csdn.net/qq_27790011/article/details/103015306
  mysql:
    image: mysql:8.0.28
    container_name: mysql # 容器名为'mysql'
    restart: always # 指定容器退出后的重启策略为始终重启
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录，要确保先创建好
      - /home/docker/volumes/mysql/logs:/var/log/mysql
      - /home/docker/volumes/mysql/data:/var/lib/mysql
      - /home/docker/volumes/mysql/conf:/etc/mysql/conf.d
    environment: # 设置环境变量,相当于docker run命令中的-e
      # mysql密码
      MYSQL_ROOT_PASSWORD: 123456
    ports: # 映射端口
      - 3306:3306

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes --requirepass "123456"
    ports:
      - "6379:6379"
    volumes:
      - /home/docker/volumes/redis/data:/data

  elasticsearch:
    image: elasticsearch-with-ik:7.9.3
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch-docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/docker/volumes/elasticsearch/data:/opt/modules/elasticsearch/node/elasticsearch/data
      - /home/docker/volumes/elasticsearch/elasticsearch.yml:/opt/modules/elasticsearch/node/elasticsearch/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300

  nowander:
    # 指定服务使用的镜像
    image: nowander:0.0.1-SNAPSHOT
    # 指定容器名称
    container_name: nowander
    # 指定服务运行的端口
    ports:
      - 8080:8080
    # 指定容器中需要挂载的文件
    volumes:
      - /home/docker/volumes/nowander/etc/localtime:/etc/localtime
      - /home/docker/volumes/nowander/logs:/var/logs
      - /home/docker/volumes/nownader/jar:/data/jar
    # java项目的环境变量，yml文件配置
    environment:
      - SPRING_REDIS_HOST=127.0.0.1
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/nowander?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    entrypoint: java -jar /data/jar/nowander.jar
    depends_on:
      - mysql
      - elasticsearch
      - redis
