version: '3'
services:
  # 参考：
  # https://juejin.cn/post/6844903872557760526
  # https://blog.csdn.net/qq_27790011/article/details/103015306
  # https://blog.csdn.net/weixin_44953227/article/details/117997825
  nowander:
    image: nowander:0.0.1
    # 指定容器名称
    container_name: nowander
    restart: always
    # 指定服务运行的端口
    ports:
      - 8081:8080
    # 指定容器中需要挂载的文件
    volumes:
      - /var/lib/docker/volumes/nowander/logs:/var/logs
    # java项目的环境变量，yml文件配置
    environment:
      - SPRING_REDIS_HOST=127.0.0.1
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://119.23.214.198:3306/nowander?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      - SPRING_DATASOURCE_USERNAME=nowander_user
      - SPRING_DATASOURCE_PASSWORD=12345678
    depends_on:
      - elasticsearch
      - redis
