@startuml
left to right direction

actor 系统管理员 as admin
actor 举办方 as organizer

usecase (创建组件) as component_create
usecase (修改组件状态) as component_update_state
usecase (更新组件信息) as component_update_info
usecase (获取组件信息) as component_get

admin --> component_create
admin --> component_update_state
admin --> component_update_info
admin --> component_get
organizer --> component_get

@enduml