@startuml
skinparam linetype ortho
class CompetitionController {
    + void create(Competition competition)
    + void updateCompetitionInfo(Long competitionId, Competition competition)
    + void updateCompetitionPage(Long competitionId, Page page)
    + void updateCompetitionState(Long competitionId, CompetitionState state)
    + void delete(Competition competition)
    + Competition findById(Long competitionId)
}
class CompetitionAuthController {
    + void updateCompetitionState(Long competitionId, CompetitionState state)
    + Competition findById(Long competitionId)
}
class CompetitionPageApplicationService {
    + void create(Competition competition)
    + void updateCompetitionPage(Long competitionId, Page page)
    + void delete(Competition competition)
    + Competition findById(Long competitionId)
}
class CompetitionService {
    + void create(Competition competition)
    + void updateCompetitionInfo(Long competitionId, Competition competition)
    + void delete(Long competitionId)
    + Competition findById(Long competitionId)
}
class CompetitionRepository {
    + void create(Competition competition)
    + void updateCompetitionPage(Long competitionId, Page page)
    + void delete(Competition competition)
    + Competition findById(Long competitionId)
    + void updateCompetitionState(Long competitionId, CompetitionState state)
}
class PageService {
    + void create(Long competitionId, Page page)
    + void updateByCompetitionId(Long competitionId, Page page)
    + void deleteAllByCompetitionId(Competition competition)
    + List<Page> findAllByCompetitionId(Long competitionId)
}
class PageRepository {
    + void create(Long competitionId, Page page)
    + void updateByCompetitionId(Long competitionId, Page page)
    + void deleteAllByCompetitionId(Competition competition)
    + List<Page> findAllByCompetitionId(Long competitionId)
}
CompetitionAuthController --> CompetitionPageApplicationService
CompetitionAuthController --> CompetitionService
CompetitionController --> CompetitionService
CompetitionController --> CompetitionPageApplicationService
CompetitionPageApplicationService --> CompetitionService
CompetitionPageApplicationService --> PageService
CompetitionService --> CompetitionRepository
PageService --> PageRepository
@enduml