@startuml
class UserAuthController {
    + void submitAuthInfo(UserAuthInfo auth)
    + void updateAuthInfo(UserAuthInfo auth)
    + UserAuthInfo findByUserId(Long userId)
}
class UserAuthAdminController {
    + List<UserAuthInfo> findAll()
    + List<UserAuthInfo> findAllUnAuth()
    + void updateUserAuthState(Long userId, UserAuthState state)
}
class UserAuthService {
    + void submitAuthInfo(UserAuthInfo auth)
    + void updateAuthInfo(UserAuthInfo auth)
    + UserAuthInfo findByUserId(Long userId)
}
class UserAuthAdminService {
    + List<UserAuthInfo> findAll()
    + List<UserAuthInfo> findAllUnAuth()
    + void review()
}
class UserAuthInfoRepository {
    + void create(UserAuthInfo auth)
    + void update(UserAuthInfo auth)
    + UserAuthInfo findByUserId(Long userId)
    + List<UserAuthInfo> findAll(Long userId)
    + List<UserAuthInfo> findByUserAuthState(UserAuthState state)
}
class OssService {
    + byte[] getFile(String url)
    + List<String> findAuthInfoFileUrlByUserId(Long userId)
    + void uploadFile(byte[] data)
}

enum UserAuthState {
    UN_AUTH
    AUTHING
    AUTH_FAILED
    AUTH_SUCCEEDED
}

UserAuthAdminController --> UserAuthService
UserAuthAdminController --> UserAuthAdminService
UserAuthController --> UserAuthService
UserAuthService --> UserAuthInfoRepository
UserAuthService ..> OssService : 事件发布
UserAuthAdminService ..> OssService : 事件发布


@enduml