@startuml

actor 认证用户 as  user
participant UserAuthService
participant OSS对象存储服务 as oss
participant 数据库 as db

user -> UserAuthService ++ :上传资料
UserAuthService -> oss ++: 上传文件和图片
return 文件和图片的URL
UserAuthService -> db ++: 保存认证资料的文本数据以及文件URL
return ok
return ok
@enduml