elasticsearch:
  search:
    # 搜索的field及其权重。因为使用@Value注入所以要写成字符创的形式
    fields:
      article: "{
        'title': 4.0,
        'content': 1.0,
        'category': 3.0,
        'label1': 3.0,
        'label2': 3.0,
        'label3': 3.0,
        'label4': 3.0,
        'label5': 3.0
      }"
  highlight:
    article:
      pre-tags: <font color='red'>
      post-tags: </font>