@startuml

actor 用户 as user

activate user
user -> user ++--: 打开创建模板页面
user -> ComponetController ++: 获取所有组件
ComponetController -> ComponentService ++: 获取所有组件
return 所有组件的数据
return 所有组件的数据
deactivate user
@enduml