@startuml
skinparam linetype ortho


class PageController {
    + List<Page> findAll()
    + List<Page> findById(Long pageId)
    + void insert(Page page)
    + void updateById(Page page)
    + void deleteById(Long pageId)
}
class TemplateController {
    + List<Template> findAll()
    + List<Template> findById(Long templateId)
    + void insert(Template template)
    + void updateById(Template template)
    + void deleteById(Long templateId)
}
class TemplatePageApplicationService {
    + void insert(Template template)
    + void updateById(Template template)
    - void checkComponentAvaliable(Long componentId)
}
class TemplatePageService {
    + List<Template> findAll()
    + List<Template> findById(Long templateId)
    + void insert(Template template)
    + void updateById(Template template)
    + void deleteById(Long templateId)
}

class TemplateRepository {
    + List<Template> findAll()
    + List<Template> findById(Long templateId)
    + void insert(Template template)
    + void updateById(Template template)
    + void deleteById(Long templateId)
}


class ComponentInstanceService {
     + List<ComponentInstance> findAllByComponentId(Long componentId)
     + List<ComponentInstance> findAllByTemplateId(Long templateId)
     + List<ComponentInstance> findAllByPageId(Long pageId)
     + void deleteAllByComponentId(Long componentId)
     + void deleteAllByTemplateId(Long templateId)
     + void   deleteAllByPageId(Long pageId)
 }
class PageRepository {
    + List<Page> findAll()
    + List<Page> findById(Long pageId)
    + void insert(Page page)
    + void updateById(Page page)
    + void deleteById(Long pageId)
}

class ComponentService {
    + Component findById(Long componentId)
}

TemplatePageApplicationService --> ComponentService

TemplateController --> TemplatePageApplicationService
PageController --> TemplatePageApplicationService
TemplatePageApplicationService --> TemplatePageService
TemplateController --> TemplatePageService
PageController --> TemplatePageService

TemplatePageService ---> TemplateRepository
TemplatePageService --> ComponentInstanceService
TemplatePageService ---> PageRepository
@enduml