@startuml
left to right direction

actor 举办方 as organizer

usecase (自定义页面模板) as templates_create
usecase (页面模板管理) as template_manage
usecase (页面创建) as page_create
usecase (页面管理) as page_manage

organizer --> templates_create
organizer --> template_manage
organizer --> page_create
organizer --> page_manage


@enduml