@startuml
entity Template {
    - Long id
    - String name
    - String thumbnail
    - Page page
}
entity Page {
    - Long id
    - String title
    - Integer deviceType
    - Integer width
    - Integer height
    - Object background // 背景
    - List<ComponentInstance> componentInstances
    - List<Component> componentMetas
}
entity Component {
    - Long id
    - String name
    - String thumbnail
    - Boolean container //是否容器组件
    - Integer displayOrder //组件显示顺序排序
    - String description
    - Object propsSchema //组件可配置属性
    - Object editorSchema //编辑状态配置
    - Object initialConfig //组件初始化配置
    - String packageUrl //组件源码包
    - String jsUrl
    - String cssUrl
    - String packageHash //包hash
    - List dataSources //组件拓展属性
}
entity ComponentInstance {
     - Long id;
     - String componentMetaName;
     - Object style;//组件实例样式
     - Object props;//组件实例属性值
     - Object position; //组件实例位置
     - Boolean deletable;
     - Boolean movable; //是否可移动
     - Boolean resizable;//是否可调整大小
     - Object dataSource;//数据源
}
entity Material {
    - UUID id;
    - String name;
    - MaterialType type; //类型:1=pdf, 2=图片, 3=视频, 4=多音轨视频, 5=音频
    - String contentType; //文件格式
    - String coverUrl;//封面地址
    - String fileUrl;//文件地址
    - Long fileSize;//文件大小
    - String fileMd5;//文件MD5
}
@enduml