@startuml
autonumber
title 定时任务到期执行
participant 服务器 as server
participant 其他服务器 as otherServer
collections redis as redis
collections 数据库 as db
actor 用户 as user

server -> server ++: 定时任务到期执行，开启事务
server -> server ++--: 执行任务


server -> redis++: redis分布式锁，锁住这个定时任务
return ok

== redis job lock ==

note right
分布式锁保证只有一台机器
能保存定时任务的执行结果
end note

server -> redis ++: 获取定时任务的信息，用于检查
return 定时任务的信息
server -> server ++--: 检查定时任务是否为空、是否已改变

alt #LightBlue 定时任务不为空，且未发生改变
    server -> user  : 推送定时任务结果
    activate user
    deactivate user
    server -> db ++: 任务执行结果保存到数据库
    return ok

else #Linen 定时任务为空，说明定时任务已完成
    server -> server ++--: 回滚事务，不做任何操作

else #Pink 定时任务发生改变
    server ->> server ++--: 回滚事务，并根据最新的数据，异步创建定时任务

end

server -> redis ++ : redis 释放分布式锁
return ok
== redis job unlock ==
server -> server --: 结束事务

@enduml